name: test nodl

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # windows testing is broken, re-add when the following is resolved
        # https://github.com/ros-tooling/action-ros-ci/issues/79
        os:
          - macos-latest
        ros_distribution:
          - foxy
    steps:
      - uses: actions/checkout@v2

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@0.0.20
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Extra Dependencies
        run: |
          pip3 install lxml

      - name: Run Tests
        uses: ros-tooling/action-ros-ci@0.0.16
        id: action_ros_ci_step
        with:
          package-name: nodl_python ros2nodl

      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()

  build-docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@2c05014

      - name: Run Tests
        uses: ros-tooling/action-ros-ci@0.0.16
        id: action_ros_ci_step
        with:
          package-name: nodl_python ros2nodl

      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()

